@baseUrl = https://localhost:5001/v1/customers
@correlationId = {{$guid}}
@id = ITkLfGqNLei4dh0kwP5qv

### Creates a Customer
POST {{baseUrl}} HTTP/1.1
X-Correlation-Id: {{correlationId}}
Content-Type: application/json

{
  "name": "John Doe #3",
  "phoneNumber": "+9876543210",
  "email": "doe@john.com"
}

### Get All Customers
GET {{baseUrl}}?pageSize=-1 HTTP/1.1
X-Correlation-Id: {{correlationId}}
