@baseUrl = https://localhost:5001/v1/posts
@correlationId = {{$guid}}
@timeout = 10000

@postId = {{$guid}}

### Create a New Post
POST {{baseUrl}}
X-Correlation-Id: {{correlationId}}
Content-Type: application/json

{
  "title": "Understanding Minimal APIs in ASP.NET",
  "content": "This post explains how to build lightweight APIs with ASP.NET.",
  "author": {
    "name": "Alice Johnson",
    "email": "alice.johnson@example.com"
  }
}

### Get Post and comments
GET {{baseUrl}}/{{postId}}
X-Correlation-Id: {{correlationId}}
Content-Type: application/json

### Add a Comment to a Post
POST {{baseUrl}}/{{postId}}/comment
X-Correlation-Id: {{correlationId}}
Content-Type: application/json

{
  "content": "Great article! Thanks for sharing.",
  "author": {
    "name": "Bob Smith",
    "email": "bob.smith@example.com"
  }
}