@baseUrl = https://localhost:5001/v1/orders
@correlationId = {{$guid}}
@id = ITkLfGqNLei4dh0kwP5qv

### Creates an Order
POST {{baseUrl}} HTTP/1.1
X-Correlation-Id: {{correlationId}}
Content-Type: application/json

{
  "customerId": "6wzFoemOub4eIbMP5vE5r",
  "products": [
    {
      "productId": "B33h2xAcJhnbbrg4Rk8mqo",
      "quantity": 1,
      "total": 1
    }
  ]
}

### Get All Orders
GET {{baseUrl}}?pageSize=-1 HTTP/1.1
X-Correlation-Id: {{correlationId}}