@baseUrl = https://localhost:5001/v1/comments
@correlationId = {{$guid}}
@timeout = 10000

@commentId = {{$guid}}

### Update Comment Status
PATCH {{baseUrl}}/{{commentId}}/status
Content-Type: application/json

{
  "status": "Approved"
}

### Delete a Comment
DELETE {{baseUrl}}/{{commentId}}