@baseUrl = https://localhost:5001/v1/products
@correlationId = {{$guid}}
@id = ITkLfGqNLei4dh0kwP5qv

### Creates a Product
POST {{baseUrl}} HTTP/1.1
X-Correlation-Id: {{correlationId}}
Content-Type: application/json

{
  "name": "Product 01",
  "description": "Description of the product.",
  "price": 19.90
}

### Get All Products
GET {{baseUrl}}?pageSize=-1 HTTP/1.1
X-Correlation-Id: {{correlationId}}
