// <auto-generated />
using System;
using FwksLabs.Boilerplate.Infra.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FwksLabs.Boilerplate.Tools.Migrations.History
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250309052900_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FwksLabs.Boilerplate.Core.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Comments");

                    b.HasIndex("PostId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("IX_UK_Comments");

                    b.ToTable("Comments", "App");
                });

            modelBuilder.Entity("FwksLabs.Boilerplate.Core.Entities.PostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Posts");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("IX_UK_Posts");

                    b.ToTable("Posts", "App");
                });

            modelBuilder.Entity("FwksLabs.Boilerplate.Core.Entities.CommentEntity", b =>
                {
                    b.HasOne("FwksLabs.Boilerplate.Core.Entities.PostEntity", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FwksLabs.Boilerplate.Core.ValueObjects.AuthorValueObject", "Author", b1 =>
                        {
                            b1.Property<Guid>("CommentEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CommentEntityId");

                            b1.ToTable("Comments", "App");

                            b1.ToJson("Author");

                            b1.WithOwner()
                                .HasForeignKey("CommentEntityId");
                        });

                    b.Navigation("Author")
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FwksLabs.Boilerplate.Core.Entities.PostEntity", b =>
                {
                    b.OwnsOne("FwksLabs.Boilerplate.Core.ValueObjects.AuthorValueObject", "Author", b1 =>
                        {
                            b1.Property<Guid>("PostEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PostEntityId");

                            b1.ToTable("Posts", "App");

                            b1.ToJson("Author");

                            b1.WithOwner()
                                .HasForeignKey("PostEntityId");
                        });

                    b.Navigation("Author")
                        .IsRequired();
                });

            modelBuilder.Entity("FwksLabs.Boilerplate.Core.Entities.PostEntity", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
