name: Publish Libs NuGet Package

on:
  push:
    tags:
      - "release-*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changes in libs folder
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/libs/src/'; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Stop if no relevant changes
        if: env.CHANGED == 'false'
        run: echo "No changes in /apps/libs/src/. Skipping publish." && exit 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/release-}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkgs /p:Version=${{ env.VERSION }}

      - name: Push NuGet package to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GH_NUGET_TOKEN }} --skip-duplicate
